[package]
name = "batch_renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
kamadak-exif = "0.5.5"
walkdir = "2.4.0"
